item { 
	name:'GoDown'
	id:1
}
item { 
	name:'Heart'
	id:2
}
item { 
	name:'LiveLong'
	id:3
}
item { 
	name:'Peace'
	id:4
}
item { 
	name:'Pray'
	id:5
}
item { 
	name:'Rock'
	id:6
}
item { 
	name:'ThumbsDown'
	id:7
}
item { 
	name:'ThumbsUp'
	id:8
}
item { 
	name:'GoUp'
	id:9
}
